### ISSUE TITLE
Eorzea Weather is down 

### ISSUE THREAD

**Issue by shugo384** [eorzea-weather/eorzea-weather#1040]
Hello i wanted to let you know the Eorzea Weather site is down!
https://i.imgur.com/PBvegcJ.png

**Comment by flowercartelet** [comment]
Oops. It seems that our Vercel account was referencing my old card and failed to renew my subscription. I registered a new card and it seems to have been restored.

**Comment by shugo384** [comment]
thank you so much alot of people like the site!
